# Generated by Django 3.2.9 on 2021-11-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_img', '0002_auto_20211104_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='img',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='img',
            name='parent_picture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='img',
            name='picture',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='img',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
