# Generated by Django 3.2.9 on 2021-11-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_img', '0003_auto_20211104_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='picture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
