# Generated by Django 3.2.9 on 2021-11-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_img', '0006_alter_img_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
